/**
 * Long-form prose for the docs page. Kept out of the OpenAPI document because
 * it is narrative rather than machine-readable, and out of the renderer
 * because the renderer is about layout.
 */

export interface GuideSection {
  id: string;
  title: string;
  /** Markdown subset — see docs/markdown.ts. */
  body: string;
  /** Optional labelled code samples rendered as a tab strip. */
  samples?: Array<{ label: string; code: string }>;
  /** Optional two-column reference table. */
  table?: { columns: string[]; rows: string[][] };
}

export function authenticationGuide(apiUrl: string): GuideSection {
  return {
  id: "authentication",
  title: "Authentication",
  body: [
    "Every endpoint except public tracking and this page needs an **access token**.",
    "",
    "Log in once with your panel credentials, then send the token on every call:",
    "",
    "```",
    "Authorization: Bearer <accessToken>",
    "```",
    "",
    "Access tokens are short-lived — 15 minutes by default. When one expires the API answers",
    "`401 Authentication required`; log in again to get a fresh token. A sensible client caches the",
    "token and re-logs in on the first 401 rather than on a timer.",
    "",
    "**Your account needs a password.** Login is the only way to mint a token, so an account created",
    "through Google sign-in has to set one first, in the panel under **Settings → Change Password**.",
    "",
    "**Do not embed credentials in a browser or mobile client.** Log in from your server, keep the token",
    "there, and treat it like a password. A token carries the full permissions of the account it was",
    "issued to.",
    "",
    "Login is rate limited to 10 attempts per 15 minutes per IP.",
  ].join("\n"),
  samples: [
    {
      label: "cURL",
      code: [
        "# 1. Exchange credentials for a token",
        `curl -X POST '${apiUrl}/auth/login' \\`,
        "  -H 'Content-Type: application/json' \\",
        "  -d '{\"identifier\":\"seller@yourbrand.in\",\"password\":\"your-password\"}'",
        "",
        "# 2. Use it",
        `curl '${apiUrl}/orders?limit=5' \\`,
        "  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'",
      ].join("\n"),
    },
    {
      label: "Node.js",
      code: [
        `const login = await fetch('${apiUrl}/auth/login', {`,
        "  method: 'POST',",
        "  headers: { 'Content-Type': 'application/json' },",
        "  body: JSON.stringify({ identifier: process.env.BOX_BEYOND_USER, password: process.env.BOX_BEYOND_PASS }),",
        "});",
        "const { accessToken } = await login.json();",
        "",
        `const orders = await fetch('${apiUrl}/orders?limit=5', {`,
        "  headers: { Authorization: `Bearer ${accessToken}` },",
        "});",
        "console.log(await orders.json());",
      ].join("\n"),
    },
    {
      label: "Python",
      code: [
        "import os, requests",
        "",
        `BASE = '${apiUrl}'`,
        "",
        "token = requests.post(f'{BASE}/auth/login', json={",
        "    'identifier': os.environ['BOX_BEYOND_USER'],",
        "    'password': os.environ['BOX_BEYOND_PASS'],",
        "}).json()['accessToken']",
        "",
        "orders = requests.get(f'{BASE}/orders', params={'limit': 5},",
        "                      headers={'Authorization': f'Bearer {token}'})",
        "print(orders.json())",
      ].join("\n"),
    },
  ],
  };
}

export const ERRORS_GUIDE: GuideSection = {
  id: "errors",
  title: "Errors",
  body: [
    "The HTTP status is the contract; the body explains it.",
    "",
    "Request-validation failures answer `400` with a field-level `errors[]` array — `path` names the field",
    "that failed and `msg` is the message to show. Everything else answers with a single `error` string.",
    "",
    "A `502` from an order endpoint means the **courier** rejected the request, not that Searchcraft failed. Those",
    "are safe to retry once the underlying problem is fixed — nothing is charged and no order is stored when a",
    "booking is rejected.",
  ].join("\n"),
  table: {
    columns: ["Status", "Meaning", "What to do"],
    rows: [
      ["200 / 201 / 202", "Success. `202` means the work was queued, not finished.", "Continue."],
      ["400", "Validation failed.", "Read `errors[]`, fix the field, resend."],
      ["401", "Token missing, malformed or expired.", "Refresh the token and retry once."],
      ["402", "Wallet balance below the shipment charge.", "Top up, then retry."],
      ["403", "KYC not approved, or the resource belongs to another account.", "Do not retry — resolve the account state."],
      ["404", "No such resource on this account.", "Do not retry."],
      ["409", "Conflict — duplicate `orderId`, duplicate webhook URL, limit reached.", "Change the input; retrying as-is will fail again."],
      ["429", "Rate limit hit.", "Back off and retry after the window."],
      ["502", "The courier rejected or failed the request.", "Safe to retry after fixing the cause."],
      ["500", "Unexpected server error.", "Retry with backoff; contact support if it persists."],
    ],
  },
};

export const WEBHOOKS_GUIDE: GuideSection = {
  id: "webhook-events",
  title: "Webhook events",
  body: [
    "Instead of polling us for order status, give us a URL and we push every change to it as it happens.",
    "",
    "**Turning it on**",
    "",
    "Webhooks can be set up from the seller panel or fully through the API. The panel path takes about a minute:",
    "",
    "1. Sign in to the panel and open **Settings → Webhooks**.",
    "2. Click **Add endpoint** and paste your HTTPS URL. There is nothing to subscribe to — one URL receives the whole order lifecycle.",
    "3. Copy the **signing secret** shown on the confirmation screen. It is displayed in full exactly once; if you lose it, use **Rotate signing secret** to issue a new one.",
    "4. Click **Send test** on the endpoint, pick the status you want to simulate, and check that your handler accepts it. The response your server gave is shown right there.",
    "5. Go live. **View log** on the endpoint shows every event we sent, what you replied, and a **Send this event again** button for anything that failed.",
    "",
    "API clients can do the same with `POST /webhooks`, `POST /webhooks/:id/test`, `GET /webhooks/deliveries` and `POST /webhooks/deliveries/:deliveryId/redeliver`.",
    "",
    "**Why admins have Webhook Deliveries**",
    "",
    "The admin panel is the operator view across every seller endpoint. It shows which sellers have endpoints, which deliveries are pending, successful or failed, the HTTP status/body returned by the client's server, and lets support replay a delivery after the client fixes their endpoint.",
    "",
    "You can register up to 5 endpoints, pause one without deleting it, and edit the URL at any time.",
    "",
    "**Responding**",
    "",
    "Answer any 2xx as soon as you have **stored** the event — do your own processing afterwards. Anything",
    "other than a 2xx, or no answer within 10 seconds, counts as a failure and is retried. Redirects are not",
    "followed: register the final URL.",
    "",
    "**Retries**",
    "",
    "A failed delivery is retried 4 more times — after 1 minute, 5 minutes, 30 minutes and 2 hours. The",
    "backoff is stored, not held in memory, so it survives our deploys and restarts. After the fifth attempt",
    "the delivery is marked failed and stops; you can still replay it yourself from the delivery log.",
    "",
    "**Things a correct handler does**",
    "",
    "- **Verify the signature** before parsing, using the raw request body. See the samples below.",
    "- **De-duplicate on the envelope `id`.** A retry — or a replay you trigger from the panel — resends the same `id`, and at-least-once delivery means you will see repeats.",
    "- **Do not rely on arrival order.** Couriers backfill scans, and a retried event can land after a newer one. Use `data.event_timestamp` and `data.status` to decide what is current, never the order events arrive in.",
    "- **Key on `data.order_id`** (your own reference) or `data.shipment_id` (ours). Both are stable for the life of the shipment.",
  ].join("\n"),
};

export const SIGNATURE_GUIDE: GuideSection = {
  id: "webhook-signatures",
  title: "Verifying a signature",
  body: [
    "Every delivery carries an `X-Searchcraft-Signature` header:",
    "",
    "```",
    "X-Searchcraft-Signature: t=1756199673,v1=8f2c...e91",
    "```",
    "",
    "`t` is the send time in Unix seconds. `v1` is `HMAC-SHA256(secret, t + \".\" + rawBody)` in lowercase hex.",
    "",
    "Compute the same value over the **raw request body** — the exact bytes, before any JSON parsing or",
    "re-serialisation. Comparing a re-encoded body will fail for reasons that are painful to debug.",
    "",
    "Compare with a constant-time function, and reject anything whose `t` is more than a few minutes old:",
    "the timestamp is inside the signed string precisely so a captured delivery cannot be replayed later.",
    "",
    "The older `X-Webhook-Signature` header (a bare HMAC of the body, no timestamp) is still sent for",
    "backward compatibility. It is **deprecated** — it offers no replay protection. Verify `v1`.",
  ].join("\n"),
  samples: [
    {
      label: "Node.js",
      code: [
        "import crypto from 'node:crypto';",
        "import express from 'express';",
        "",
        "const app = express();",
        "",
        "// express.raw — the signature is over the bytes we received, not a re-encoding.",
        "app.post('/hooks/searchcraft', express.raw({ type: 'application/json' }), (req, res) => {",
        "  const header = req.get('X-Searchcraft-Signature') ?? '';",
        "  const parts = Object.fromEntries(header.split(',').map((p) => p.split('=')));",
        "",
        "  const expected = crypto",
        "    .createHmac('sha256', process.env.BOX_BEYOND_WEBHOOK_SECRET)",
        "    .update(`${parts.t}.${req.body.toString('utf8')}`)",
        "    .digest('hex');",
        "",
        "  const received = Buffer.from(parts.v1 ?? '', 'hex');",
        "  const computed = Buffer.from(expected, 'hex');",
        "  const signatureOk =",
        "    received.length === computed.length && crypto.timingSafeEqual(received, computed);",
        "  const fresh = Math.abs(Date.now() / 1000 - Number(parts.t)) < 300;",
        "",
        "  if (!signatureOk || !fresh) return res.status(400).send('invalid signature');",
        "",
        "  const event = JSON.parse(req.body.toString('utf8'));",
        "  // Store event.id and ack straight away — process afterwards.",
        "  if (!alreadySeen(event.id)) enqueue(event);",
        "  res.sendStatus(200);",
        "});",
      ].join("\n"),
    },
    {
      label: "Python",
      code: [
        "import hashlib, hmac, json, time",
        "from flask import Flask, request, abort",
        "",
        "app = Flask(__name__)",
        "SECRET = os.environ['BOX_BEYOND_WEBHOOK_SECRET'].encode()",
        "",
        "@app.post('/hooks/searchcraft')",
        "def box_and_beyond_webhook():",
        "    raw = request.get_data()  # raw bytes, not request.json",
        "    parts = dict(p.split('=', 1) for p in request.headers.get('X-Searchcraft-Signature', '').split(','))",
        "",
        "    signed = parts.get('t', '').encode() + b'.' + raw",
        "    expected = hmac.new(SECRET, signed, hashlib.sha256).hexdigest()",
        "",
        "    fresh = abs(time.time() - int(parts.get('t', 0))) < 300",
        "    if not fresh or not hmac.compare_digest(expected, parts.get('v1', '')):",
        "        abort(400)",
        "",
        "    event = json.loads(raw)",
        "    if not already_seen(event['id']):",
        "        enqueue(event)",
        "    return '', 200",
      ].join("\n"),
    },
    {
      label: "PHP",
      code: [
        "<?php",
        "$raw    = file_get_contents('php://input');   // raw body, not $_POST",
        "$header = $_SERVER['HTTP_X_BOX_AND_BEYOND_SIGNATURE'] ?? '';",
        "",
        "parse_str(str_replace(',', '&', $header), $parts);",
        "",
        "$expected = hash_hmac('sha256', $parts['t'] . '.' . $raw, getenv('BOX_BEYOND_WEBHOOK_SECRET'));",
        "$fresh    = abs(time() - (int) ($parts['t'] ?? 0)) < 300;",
        "",
        "if (!$fresh || !hash_equals($expected, $parts['v1'] ?? '')) {",
        "    http_response_code(400);",
        "    exit('invalid signature');",
        "}",
        "",
        "$event = json_decode($raw, true);",
        "if (!alreadySeen($event['id'])) {",
        "    enqueue($event);",
        "}",
        "http_response_code(200);",
      ].join("\n"),
    },
  ],
  table: {
    columns: ["Header", "Value"],
    rows: [
      ["X-Searchcraft-Event", "Event name, e.g. `order.delivered`."],
      ["X-Searchcraft-Event-Id", "`evt_…` — the same value as the envelope `id`. Stable across retries and across endpoints. De-duplicate on this."],
      ["X-Searchcraft-Delivery-Id", "Identifies this one attempt. Quote it to support, or find it in the panel under **Settings → Webhooks → View log**."],
      ["X-Searchcraft-Attempt", "Attempt number, `1` to `5`."],
      ["X-Searchcraft-Timestamp", "Send time, ISO-8601."],
      ["X-Searchcraft-Signature", "`t=<unix seconds>,v1=<hex HMAC-SHA256>`. Verify this."],
      ["X-Webhook-Signature", "Deprecated — bare HMAC of the body, no replay protection."],
      ["User-Agent", "`Searchcraft-Webhooks/1.0`"],
    ],
  },
};
